apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xau-trading-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thaisonnguyenbt2/exness
    targetRevision: main
    path: k8s/local # Points to the overlay folder, which inherits from the base K8s folder
  destination:
    server: https://kubernetes.default.svc
    namespace: exness-trading
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true