apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra.yaml
  - config.yaml
  - data-ingest.yaml
  - ai-notification.yaml
  - orchestrator.yaml
  - frontend-ingress.yaml
