apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra.yaml
  - config.yaml
  - data-ingest.yaml
  - ai-notification.yaml
  - orchestrator.yaml
  - frontend-ingress.yaml

images:
  - name: ocir.io/tenancy/data-ingest
    newTag: latest
  - name: ocir.io/tenancy/ai-analyzer
    newTag: latest
  - name: ocir.io/tenancy/notification
    newTag: latest
  - name: ocir.io/tenancy/orchestrator
    newTag: latest
  - name: ocir.io/tenancy/frontend
    newTag: latest
